FROM oven/bun:1-alpine AS prod

WORKDIR /app/frontend

COPY frontend/package.json ./
COPY frontend/astro.config.mjs ./
COPY frontend/tsconfig.json ./
RUN bun add astro @astrojs/node

COPY frontend/src ./src
COPY shared /app/shared

ARG PUBLIC_ENVIRONMENT=production
ARG PUBLIC_API_URL=http://localhost:3005
ENV PUBLIC_ENVIRONMENT=$PUBLIC_ENVIRONMENT
ENV PUBLIC_API_URL=$PUBLIC_API_URL

RUN bun run astro build

EXPOSE 4321

CMD bun run node ./dist/server/entry.mjs
