FROM oven/bun:1-alpine AS dev

WORKDIR /app/frontend

COPY frontend/package.json ./
COPY frontend/astro.config.mjs ./
RUN bun add astro

COPY frontend/src ./src
COPY shared /app/shared

EXPOSE 4321

CMD ["bun", "run", "astro", "dev", "--host"]
