services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      target: dev
    ports:
      - "${FRONTEND_PORT}:4321"
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_NAME=${APP_NAME}
      - PUBLIC_ENVIRONMENT=${ENVIRONMENT}
      - API_URL=http://api-dev:3000
    depends_on:
      - api-dev
    networks:
      internal:
      edge:
        aliases:
          - test-colpruebas-origin
    restart: unless-stopped

  api-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - NODE_ENV=${NODE_ENV}
      - APP_NAME=${APP_NAME}
      - ENVIRONMENT=${ENVIRONMENT}
      - PORT=3000
    networks:
      - internal
    restart: unless-stopped
