FROM oven/bun:1-alpine

WORKDIR /app/backend

COPY backend/package.json ./
COPY backend/bun.lock ./
RUN bun install --frozen-lockfile

COPY backend/src ./app-src
COPY shared /app/shared

EXPOSE 3000

CMD ["bun", "--watch", "run", "app-src/index.ts"]
